version: '3.2'

services:
  hackernews_django:
    build: .
    container_name: hackernews_django
    volumes:
      - ./:/app
    command: gunicorn --bind :8000 django_integration_test.wsgi:application
    ports:
      - '80:8000'
    env_file:
      - .env
